name: Run Tests on Build Artifacts

on:
  workflow_run:
    workflows: [Build and Upload Artifacts]
    types: [completed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
